name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update_release_and_change_log:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission.
      # https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
            github-token: ${{ secrets.github_token }}
#            create-summary: true

      - name: release drafter
        uses: release-drafter/release-drafter@v6
        if: steps.changelog.outputs.skipped != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
